%\VignetteIndexEntry{sjemea}
%\VignetteKeywords{MEA}
%\VignettePackage{sjemea}
%\VignetteEngine{knitr::knitr}
\documentclass{article}
\usepackage{mathpazo}
\renewcommand{\sfdefault}{lmss}
\renewcommand{\ttdefault}{lmtt}
\usepackage[T1]{fontenc}
\usepackage[a4paper,left=2cm,right=4cm,top=2cm,bottom=2cm]{geometry}
\usepackage{setspace}
\usepackage{listings}
\usepackage{verbatim}

\usepackage{xspace,amsmath}
\newcommand{\um}{\ensuremath{\mu \text{m}}\xspace}
\usepackage{url}
\usepackage[authoryear]{natbib}
\newcommand{\dynamic}{(Dynamic)}
\newcommand{\static}{(Static)}
\newcommand{\hdfgroup}[1]{\texttt{#1}}
%% Place all figures at end of paper?
%%\usepackage[noheads,nomarkers]{endfloat}

\begin{document}

\onehalfspacing
\title{meadq package: From A to Z }

\author{Diana Hall}
\date{\today}

\maketitle


\section*{Installation}
To install this package, and then view this introductory vignette, do:

<<install-meadq,eval=FALSE,echo=TRUE>>=
tarfile.path = "F:/R/Rpackage_meadq/meadq_1.0.1.tar.gz"
install.packages(pkgs = tarfile.path, type="source", repos = NULL)
vignette('meadq-intro', package='meadq')
@

Alternatively, if you want to get the latest version of the package,
you can install it in the following manner:
<<install-meadq-github,eval=FALSE,echo=TRUE>>=
install.package("devtools") # note: need R v.>=3.1.0
# to install devtools, use CRAN
require(devtools)
install_github("dianaransomhall/meadq")
@ 
You can browse the package sources via the URL
\url{http://github.com/dianaransomhall/meadq}.


\section*{Setup}
This file is a vignette, written in R, as a reproducible research
document.

<<setup,message=FALSE>>=
require(meadq)
require(knitr)
opts_chunk$set(cache=TRUE)
opts_chunk$set(dev='pdf')
@

\section*{Introduction}

This is a short introduction to the abilities of the meadq package
for analysis of multielectrode array data.  It is not a comprehensive
guide, but simply gives examples of what can be done with the package.
The package contains some example data sets which are used here to
demonstrate various routines.  

\subsection*{Help pages}
A list of help pages associated with the package is given by
\verb+help(package='meadq')+ command:
<<help,echo=FALSE>>=
cat(format(help(package='meadq')), sep = '\n') #need to grab output.
@


\section*{creating .h5 Files from text files of spike trains}

Convert the recorded data, which may be in a proprietary or otherwise non universal file type, into a type which may be read in by various softwares.  Following suggestions from the "program on Standards for Datasharing" by the International neuroinformatics coordinating facility \url{datasharing.incf.ord/ep/HDF5_data_standard}, code is provided to convert axion alpha map files to .h5 files that link spike train to meta-data about the experiment.  Current functionality is restricted to experimental meta data limited to a handful of variabes. However, additional information may be built in by creating a new function. 

<<>>=
# For example, choose .mapTimestamps: 
print( system.file( "extdata", "ON_20140205_MW1007-26_DIV07_001.mapTimestamps",
                    package= "meadq") )
make.axion.map.to.h5.dh()
@

\subsection{What is the ``s[[i]]'' object?}

A convention of the program is that all data referring to a recording
is stored within an object of class \texttt{mm.s}, which is actually a
list.  So, when new data/results are collected for a recording, I tend
to add the new information into that object (e.g. see how burst
analysis results are stored).

The most important items in the list are:
\begin{description}
\item[NCells] The number of units in the recording.
\item[rec.time] The start and end time of the recording.
\item[spikes] A list of vectors.  Element $i$ of the list is the
  vector of spike trains for unit $i$.  Each spike train is ordered, smallest first.
\item[nspikes] A vector.  $nspikes[i]$ is the number of spikes in
  train i.
\item[layout] Information regarding the spatial layout of the units.
\end{description}

\section*{Burst analysis}

Burst identification is done with:
\begin{enumerate}
\item Max Interval method, as described by Neuroexplorer \citep{neuroexplorer}

\end{enumerate}

The MaxInterval method.
<<bursts>>=
data.file <- system.file("data", "example_ont_data.rda",
package = "meadq")
load(data.file)
@

So, for example, for electrode 2, we see the following bursts (just
taking the head as there are many of them.  We can also easily plot
the number of bursts on each electrode.

<<show-burst-info>>=
#head(s[[3]]$allb[[2]])
#nbursts <- sapply(s[[3]]$allb, nrow)
#plot(nbursts, xlab='Electrode number', ylab='Number of bursts',
#     bty='n', las=1)
@


Once bursts are computed the resulting burst information can be
visualized on a raster assuming that the burst information is stored
in the \verb+s$allb+ component of the object.  Here we ask to see the
burst information for twenty seconds of data from just the first five trains.

<<burst-raster>>=
#plot(s[[3]], beg=100, end=200, show.bursts=TRUE, whichcells=1:5)
@

Bursts are indicated with a red horizontal line, and the blue number
indicates the number of spikes in the burst.


Note: a Hidden-Markov Model (HMM) for burst analysis in R \citep{Tokdar2010}
is available in the following package:
\url{http://www.stat.duke.edu/~st118/Software/}.

can be used within this package, but in principle (computation time
aside as I expect an HMM to be slow) there should be no issue.  There
is also a generic ``bursts'' package:
\url{http://cran.r-project.org/web/packages/bursts/bursts.pdf}.



\section*{Network spikes}

Network spikes are periodic elevations in activity across the whole
array \citep{Eytan2006}.  The following example shows how they are computed.
In the resulting graph, the population ``firing rate'' (the number of
active electrodes here) is shown on the y axis, time (in seconds) on
the x axis.  The horizontal red line is a threshold set for the
minimum number of active electrodes to determine a ``network spike''.
The blue dots are the peak of each network spikes.

The mean network spike is also shown, averaged across all the network
spikes in the recording.

<<>>=
example(compute.ns, package="sjemea")
@

\bibliographystyle{jneurosci}
\bibliography{sjemea}

\subsection*{Compiling this document}

<<eval=FALSE,include=TRUE>>=
require(knitr); knit2pdf('meadq-into.Rnw')
@




\end{document}
