
#This function reads in .h5Files the the .h5 file or .rda format.  It builds two graphs that 
# compares files.  

burst_table_Plots_comp<-function( param.file=NULL, h5Files = NULL, goodwells.ind = F,
                                  ctr.file.ind=1, trt.file.ind=2){
  
  
  #load necessary packages
  library(sjemea)
  library(rhdf5)
  library(lattice)
  
  
  #get the directory containing the .h5 files
  if (is.null(h5Files) ){
    h5Files<-sort(choose.files(caption="Choose .h5 Files or choose .Rdata file") )
  }
  h5.dir<-dirname(h5Files)
  
  #set directories 
  root.dir<-dirname(dirname(h5Files[1]))
  h5.dir<-dirname(h5Files)
  
  #create directory for bursting
  dir.create(paste(root.dir,'/BurstSummary',sep='') )
  burst.dir<-paste(root.dir,'/BurstSummary',sep='')
  
  
  ###load spikes and set up parameters for burst analysis
  
  #list of parameters needed for burst algorithm
  if ( is.null(param.file) ){
    param.file<-choose.files(caption="Choose parameter file ")
    source( param.file  ) 
  }
  
  
  #filter and get burst data
  if (is.element( substring(h5Files,nchar(h5Files)-4,nchar(h5Files)), 
                  c("RData", "rdata", "Rdata", "rData","rda") ) ) {
    load( h5Files ) #load in .RData, should be called s already
  } else {
    s<-filter.spikes.burst.info(h5Files)
  }
  
  print( paste( "baseline file is", s[[ctr.file.ind]]$file) )
  print( paste("comparison file is",s[[trt.file.ind]]$file))
  
  ###########################################
  ####plot baseline vs. 1hr by channel and well
  
  #get bursting data averaged over wells
  masterSum<-get.burst.info.averaged.over.well(s, goodwells.ind = goodwells.ind) 
  
  #set file paths
  burstPlotPath = paste(burst.dir,"/baseline.1hr.Burst.Plots.pdf",sep="")
  pdf(file=burstPlotPath) 
  
  #layout
  p<-plot.mealayout.1(s[[ctr.file.ind]]$layout, use.names=T, cex=0.40)
  title(main= paste( paste("Electrode Layout"), 
                     paste("file= ",  strsplit( basename(s[[ctr.file.ind]]$file),".h5")[[1]][1], sep=""), 
                     paste("Generated by burst_table_Plots.R on ",Sys.time(),sep=""), 
                     paste("written by Diana Hall using ",R.Version()$version.string,sep=""),                               
                     sep='\n'))
  
  
  p<-plot.mealayout.1(s[[ trt.file.ind ]]$layout, use.names=T, cex=0.40)
  title(main= paste( paste("Electrode Layout"), 
                     paste("file= ",  strsplit( basename(s[[trt.file.ind]]$file),".h5")[[1]][1], sep=""), 
                     paste("Generated by burst_table_Plots.R on ",Sys.time(),sep=""), 
                     paste("written by Diana Hall using ",R.Version()$version.string,sep=""),                               
                     sep='\n'))
  
  #MFR
  p<-plot.burst.base.1hr(s,resp="meanfiringrate", resp.label="Mean Firing Rate (Hz)")
  #Mean Duration
  p<-plot.burst.base.1hr(s,resp="bs$mean.dur",resp.label="Mean Duration of Burst (s)")
  #plot of Number of bursts by channel and well  
  p<-plot.burst.base.1hr(s,resp="bs$nbursts",resp.label="Number of Bursts")
  #mean Inter Burst Interval 
  p<-plot.burst.base.1hr(s,resp="bs$mean.IBIs",resp.label="Mean IBIs (ms)")
  # mean ISI within bursts 
  p<-plot.burst.base.1hr(s,resp="bs$mean.isis",resp.label="Mean ISI w/i Bursts (s)")
  #mean burst per minute 
  p<-plot.burst.base.1hr(s,resp="bs$bursts.per.min",resp.label="Mean Burst per Minute")
  #mean spikes in a burst
  p<-plot.burst.base.1hr(s,resp="bs$mean.spikes",resp.label="Mean # Spikes/Burst")
  #% spikes in a burst
  p<-plot.burst.base.1hr(s,resp="bs$per.spikes.in.burst",resp.label="% Spikes/Burst")
  
  
  dev.off()
  
  
  
  
} #end of burst_table_Plots_comp
