
burst_table_Plots_csv<-function(){
  
  #########################
  #Table by channel and Well and table summarizing well
  
  
  #get bursting data averaged over wells
  masterSum<-get.burst.info.averaged.over.well(s)
  
  
  #************write csv table***************************
  
  ###titles
  #file titles and names
  tempTime<-c(); 
  for (i in 1:length(s)){
    tempname<-strsplit( basename(s[[i]]$file),".h5")[[1]][1]
    tempTime<-c(tempTime, substr(tempname ,nchar(tempname)-5,nchar(tempname)-4 ) )
    if (i!=1){
      csvFileAppendix<-paste(csvFileAppendix,substr(tempname ,nchar(tempname)-5,nchar(tempname)-4 ),sep="&")
    } else{
      csvFileAppendix<-substr(tempname ,nchar(tempname)-5,nchar(tempname)-4 )
    }
  }
  
  tempname<-strsplit( basename(s[[i]]$file),".h5")[[1]][1]
  h5FilePrefix<-paste( strsplit(tempname, "_")[[1]][1],strsplit(tempname, "_")[[1]][2],
                       strsplit(tempname, "_")[[1]][3],strsplit(tempname, "_")[[1]][4],sep="_")
  title<-paste( paste("bs", h5FilePrefix, csvFileAppendix , sep="_"),".csv",sep="")
  csvfile<-paste(burst.dir,title,sep="/")
  
  for (i in 1:length(s)){
    
    ##########data frame summarized over well
    #get number of object in masterSum[[1]] list
    tempdf<-c(); tempcolnames<-c()
    for (j in 2:length(masterSum[[i]])){
      tempc<-unlist(masterSum[[i]][j])
      tempdf<-cbind(tempdf,tempc)
      tempcolnames<-c(tempcolnames,names(masterSum[[i]][j]) )
    }#end of loop through masterSum list objects
    
    #need to switch around columns so first columns come first
    df<-cbind(tempdf[,20:24],tempdf[,1:18],tempdf[,19])
    colnames<-c(tempcolnames[20:24],tempcolnames[1:18],tempcolnames[19])
    colnames(df)<-colnames
    
    
    
    ##################channel by channel burst summary
    
    #meta data and misc
    #get vector of which wells are active
    wellindex<-which(is.element(names(s[[i]]$treatment), unique(s[[i]]$cw)) )
    well<-c(); treatment<-c(); size<-c(); dose<-c(); file<-c();
    for (j in wellindex){
      #repeat treatment the number of times it appears in s[[i]]$cw
      treatment<-c(treatment, rep( s[[i]]$treatment[j],sum(s[[i]]$well[j]==s[[i]]$cw) ) )
      size<-c(size, rep( s[[i]]$size[j],sum(s[[i]]$well[j]==s[[i]]$cw) ) )
      dose<-c(dose, rep( s[[i]]$dose[j],sum(s[[i]]$well[j]==s[[i]]$cw) ) )
    }#end of loop through good wells
    file<-rep(strsplit( basename(s[[1]]$file),".h5")[[1]][1], length(s[[i]]$cw))
    well<-s[[i]]$cw
    
    #channel data frame
    df2<-cbind(file,well,treatment,size,dose,as.data.frame( s[[i]]$bs[1:length(s[[i]]$bs)]) )
    
    #write to table part!
    #write a title
    
    write.table("Bursting Analysis averaged over Each Well",
                csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE) 
    
    
    write.table(paste("file= ",  strsplit( basename(s[[i]]$file),".h5")[[1]][1], sep=""),
                csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE) 
    write.table(paste("Generated by burst_table_Plots.R on ",Sys.time(),sep=""),
                csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE) 
    write.table(paste("written by Diana Hall using ",R.Version()$version.string,sep=""),
                csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    #recording time
    write.table(paste("recording time (s): [", paste(s[[i]]$rec.time[1],round(s[[i]]$rec.time[2]), sep=" ,"),
                      "]",sep=""),csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    
    #summary write data
    write.table(df,
                csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=TRUE)
    #new lines
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    
    #title
    write.table("Channel Burst Summary",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    write.table(paste("file= ",  strsplit( basename(s[[i]]$file),".h5")[[1]][1], sep=""),
                csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE) 
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    
    #channel data
    write.table(df2,
                csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=TRUE)
    #new lines
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    write.table(" ",csvfile, sep=",", append=TRUE,row.names=FALSE,col.names=FALSE)
    
    
  }#end of loop through writting tables
  
  
  
  
  
} # end of burst_table_Plot_csv

